export const tickets = [
    {
        id: 1,
        codigo:123459,
        fecha:'18/04/2023',
        aula:'T6',
        grupo:'DAW1',
        ordenador:'PC3',
        descripcion:'Error de impresora',
        alumno:'Ana Martínez',
        status: 0,
    },
    {
        id: 2,
        codigo:123460,
        fecha:'19/04/2023',
        aula:'T8',
        grupo:'DAW2',
        ordenador:'PC4',
        descripcion:'Problema de acceso a archivos',
        alumno:'Pedro Gómez',
        status: 0,
    },
    {
        id: 3,
        codigo:123461,
        fecha:'20/04/2023',
        aula:'T6',
        grupo:'DAW1',
        ordenador:'PC1',
        descripcion:'Aplicación se cierra inesperadamente',
        alumno:'Sofía Fernández',
        status: 0,
    },
    {
        id: 4,
        codigo:123462,
        fecha:'21/04/2023',
        aula:'T7',
        grupo:'DAW2',
        ordenador:'PC2',
        descripcion:'Problema de conexión a la red',
        alumno:'Luis Torres',
        status: 0,
    },
    {
        id: 5,
        codigo:123463,
        fecha:'22/04/2023',
        aula:'T8',
        grupo:'DAW1',
        ordenador:'PC3',
        descripcion:'Archivos corruptos',
        alumno:'Carolina Ramírez',
        status: 0
    },
    {
        id: 6,
        codigo: 123457,
        fecha: '16/04/2023',
        fecha_resuelto: '15/05/2023',
        aula: 'T7',
        grupo: 'DAW2',
        ordenador: 'PC1',
        descripcion: 'Problema de conexión a Internet',
        alumno: 'Maria López',
        status: 1
    },
    {
        id: 7,
        codigo: 123458,
        fecha: '17/04/2023',
        fecha_resuelto: '15/05/2023',
        aula: 'T8',
        grupo: 'DAW1',
        ordenador: 'PC2',
        descripcion: 'Pantalla en blanco',
        alumno: 'Juan Rodríguez',
        status: 1
    },
    {
        id: 8,
        codigo: 123459,
        fecha: '18/04/2023',
        fecha_resuelto: '15/05/2023',
        aula: 'T8',
        grupo: 'DAW1',
        ordenador: 'PC3',
        descripcion: 'Error de impresora',
        alumno: 'Ana Martínez',
        status: 1
    }
]